dist: focal
language: c
os:
  - linux
  - osx
env:
  - FLAGS="--enable-networking --disable-gtk3"
  - FLAGS="--enable-networking --enable-gtk3"
  - FLAGS="--disable-networking"
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq && sudo apt-get install -qq automake autoconf gcc libglib2.0-dev libcurl4-openssl-dev libgtk2.0-dev libgtk-3-dev; fi

script:
  - ./autogen.sh $FLAGS && make -j2
  - src/dopewars -v
  - src/dopewars -h
